MESSAGE(STATUS "Starting APK packaging... ${CPACK_PACKAGE_INSTALL_DIRECTORY}/${CPACK_TOPLEVEL_DIRECTORY}")

set(suffix)
if (CMAKE_HOST_WIN32)
	set(suffix ".bat")
endif()

MESSAGE(STATUS ${CPACK_TOPLEVEL_DIRECTORY}/${CPACK_PACKAGE_FILE_NAME}/MadgineLauncher)

EXECUTE_PROCESS(
	COMMAND gradle${suffix} assembleDebug COMMAND_ERROR_IS_FATAL ANY COMMAND_ECHO STDOUT OUTPUT_STRIP_TRAILING_WHITESPACE
	WORKING_DIRECTORY ${CPACK_TOPLEVEL_DIRECTORY}/${CPACK_PACKAGE_FILE_NAME}/MadgineLauncher)

EXECUTE_PROCESS(
	COMMAND ${CMAKE_COMMAND} -E copy ${CPACK_TOPLEVEL_DIRECTORY}/${CPACK_PACKAGE_FILE_NAME}/MadgineLauncher/build/outputs/apk/debug/MadgineLauncher.apk ${CPACK_PACKAGE_DIRECTORY}/${CPACK_PACKAGE_FILE_NAME}.apk)

MESSAGE(STATUS "Done")