
set(CPACK_GENERATOR External)
set(CPACK_EXTERNAL_ENABLE_STAGING ON)
file(GENERATE OUTPUT apk.cmake INPUT ${workspace_file_dir}/cpack/android/apk.cmake.in)
set(CPACK_EXTERNAL_PACKAGE_SCRIPT ${CMAKE_CURRENT_BINARY_DIR}/apk.cmake)
set(CPACK_PACKAGE_FILE_NAME  ${PROJECT_NAME}${MADGINE_CONFIGURATION_SUFFIX}-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_ANDROID_ARCH_ABI})