name: CMake on multiple platforms

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  configuration:
    name: configuration  
    runs-on: ubuntu-latest

        
    steps:
    - uses: actions/checkout@v4
      if: ${{ !env.ACT }}
      with:
        submodules: recursive
        fetch-depth: 0

        
    - uses: paulhatch/semantic-version@v5.4.0
      id: version
      if: ${{ !env.ACT }}
      with:
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
        user_format_type: "json"
        enable_prerelease_mode: true
        debug: false          

    outputs:
      platforms: "{
        \"Windows\": \"windows-latest\", 
        \"macOS\": \"macos-15\", 
        \"iOS\": \"macos-latest\", 
        \"Linux\": \"ubuntu-latest\", 
        \"Android_arm64\": \"ubuntu-latest\", 
        \"Android_x64\": \"ubuntu-latest\", 
        \"Emscripten\": \"ubuntu-latest\"}"
      presets: "{
        \"Windows\": \"Clang-RelWithDebInfo-DirectX\", 
        \"macOS\": \"RelWithDebInfo-OpenGL\", 
        \"iOS\": \"RelWithDebInfo-OpenGL\", 
        \"Linux\": \"RelWithDebInfo-OpenGL\", 
        \"Android_arm64\": \"Android-arm64-RelWithDebInfo-Vulkan\", 
        \"Android_x64\": \"Android-x64-RelWithDebInfo-Vulkan\", 
        \"Emscripten\": \"Emscripten-RelWithDebInfo-OpenGL\"}"
      version: "${{ steps.version.outputs.version }}"
      version_tag: "${{ steps.version.outputs.version_tag }}"
    
  build-plugins:
  
    needs: configuration

    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false

      matrix:
        platform: [ubuntu-latest, windows-latest, macos-15] 

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Patch Dependencies
      run: |
        echo "https://github.com/MadManStudios/MadgineSentry.git" >> ${{ github.workspace }}/dependencies.txt
   
    - name: Install Toolchain
      uses: ./.github/actions/install-toolchain
      with:
        platform: ${{ runner.os }}

    - name: Configure CMake
      env:
        MADGINE_VERSION: ${{ needs.configuration.outputs.version }}
      run: cmake --preset=RelWithDebInfo -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/out/build/RelWithDebInfo --config RelWithDebInfo -j

    - name: Test
      working-directory: ${{ github.workspace }}/out/build/RelWithDebInfo
      run: ctest --build-config RelWithDebInfo --output-on-failure

    #- name: Package
    #  working-directory: ${{ github.workspace }}/out/build/RelWithDebInfo
    #  run: cpack

    #- name: Pushing Artifacts
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: release-${{ matrix.platform }}
    #    path: |
    #        ${{ github.workspace }}/out/build/RelWithDebInfo/packages/*
    #        !${{ github.workspace }}/out/build/RelWithDebInfo/packages/_CPack_Packages/
    #    overwrite: true

    - name: Pushing Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}
        path: ${{ github.workspace }}/out/build/RelWithDebInfo/bin
        overwrite: true

  build-configs:
  
    needs: [configuration, build-plugins]

    runs-on: ${{ fromJSON(needs.configuration.outputs.platforms)[matrix.platform] }}    

    strategy:
      fail-fast: false

      matrix:
        platform: [Linux, Android_arm64, Android_x64, Emscripten, Windows, macOS, iOS]
        exclude:          
          - platform: iOS
          - platform: macOS

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Patch Dependencies
      run: |
        echo "https://github.com/MadManStudios/MadgineSentry.git" >> ${{ github.workspace }}/dependencies.txt

    - name: Fetching Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ fromJSON(needs.configuration.outputs.platforms)[matrix.platform] }}    
        path: tooling

    - name: Changing Permissions
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        chmod +x tooling/MadgineLauncher

    - name: Install Toolchain
      uses: ./.github/actions/install-toolchain
      with:
        platform: ${{ matrix.platform }}

    - name: Configure CMake
      env:
        MADGINE_VERSION: ${{ needs.configuration.outputs.version }}
      run: >
        cmake --preset=${{ fromJSON(needs.configuration.outputs.presets)[matrix.platform] }}
        -DMADGINE_PREBUILT_TOOLING=tooling
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/out/build/${{ fromJSON(needs.configuration.outputs.presets)[matrix.platform] }} --config RelWithDebInfo

    - name: Test
      working-directory: ${{ github.workspace }}/out/build/${{ fromJSON(needs.configuration.outputs.presets)[matrix.platform] }}
      run: ctest --build-config RelWithDebInfo --output-on-failure
  
    - name: Package
      working-directory: ${{ github.workspace }}/out/build/${{ fromJSON(needs.configuration.outputs.presets)[matrix.platform] }}
      run: cpack
      if: matrix.platform != 'Windows'

    - name: Pushing Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.platform }}
        path: |
            ${{ github.workspace }}/out/build/${{ fromJSON(needs.configuration.outputs.presets)[matrix.platform] }}/packages/*
            !${{ github.workspace }}/out/build/${{ fromJSON(needs.configuration.outputs.presets)[matrix.platform] }}/packages/_CPack_Packages/
        overwrite: true

  release:
    
    needs: [configuration, build-configs, build-plugins]

    runs-on: ubuntu-latest

    if: github.ref_name == 'master' && !github.event.act

    permissions:
      contents: write    

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v5
      with:
        path: ${{ github.workspace }}/packages
        pattern: release-*
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ needs.configuration.outputs.version_tag }}
        tag_name: ${{ needs.configuration.outputs.version_tag }}
        files: ${{ github.workspace }}/packages/**/*

  upload-gh-pages:
    
    needs: build-configs

    runs-on: ubuntu-latest

    if: github.event_name == 'push' && !github.event.act
            
    permissions:
      contents: write    

    steps:

    - name: Download Artifacts
      uses: actions/download-artifact@v5
      with:
        path: ${{ github.workspace }}/packages
        name: release-Emscripten
     
    
    - uses: actions/checkout@v4
      with:
        ref: 'gh-pages'
        path: 'gh-pages'

    - name: Updating gh-pages branch
      env: 
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      run: |
        cd gh-pages
        rm -rf ${{ github.ref_name }} 
        mkdir ${{ github.ref_name }} 
        unzip ${{ github.workspace }}/packages/*.zip -d ${{ github.ref_name }} 
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ${{ github.ref_name }} 
        git commit -m "Updating emscripten binaries for branch ${{ github.ref_name }} "
        git push
        curl -sL https://sentry.io/get-cli/ | sh
        sentry-cli debug-files upload -o madmanstudios -p madgine ${{ github.workspace }}/packages/*.debug.wasm
