# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build documentation

on:
  push:
    branches: [ "master", "dev" ]

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - uses: paulhatch/semantic-version@v5.4.0
      if: github.ref_name == 'master'
      id: version
      with:
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
        user_format_type: "json"
        enable_prerelease_mode: true
        debug: false          

    - name: setup
      id: setup
      run: |
        mkdir -p out/doc/doxygen
        if [[ "$GITHUB_REF_NAME" == "dev" ]]; then
          echo "version=dev" >> $GITHUB_OUTPUT
        else
          echo "version=${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT
        fi

    - uses: mattnotmitt/doxygen-action@v1.9.5
      env:
        MADGINE_VERSION: ${{ steps.setup.outputs.version }}
      with:
        doxyfile-path: 'docs/Doxyfile'

    - uses: ammaraskar/sphinx-action@master
      env:
        MADGINE_VERSION: ${{ steps.setup.outputs.version }}
      with:
        docs-folder: "."
        pre-build-command: "pip install sphinx_rtd_theme doxysphinx;doxysphinx build . out/doc/html out/doc/doxygen"
        build-command: "sphinx-build -b html . out/doc/html -c docs"

    - uses: actions/checkout@v4
      with:
        ref: 'gh-pages'
        path: 'gh-pages'

    - name: Copy static files into repository
      run: |
        rm -rf gh-pages/doc/${{ steps.setup.outputs.version }}
        mkdir -p gh-pages/doc
        cp -r out/doc/html gh-pages/doc/${{ steps.setup.outputs.version }}

        DIRS=$(find "gh-pages/doc" -mindepth 1 -maxdepth 1 -type d -printf '"%f",\n')

        rm -f gh-pages/doc/versions.js
        {
          echo "const versions = ["
          echo "$DIRS"
          echo "];"
          cat docs/versions.js
        } > gh-pages/doc/versions.js        

    - name: "Updating gh-pages branch"
      if: ${{ !env.ACT }}
      run: |
        cd gh-pages
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add doc
        git commit -m "Updating generated docs"
        git push
