# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build documentation

on:
  push:
    branches: [ "master" ]

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - uses: paulhatch/semantic-version@v5.4.0
      id: version
      with:
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
        user_format_type: "json"
        enable_prerelease_mode: true
        debug: false          

    - uses: mattnotmitt/doxygen-action@v1.9.5
      env:
        MADGINE_VERSION: ${{ steps.version.outputs.version }}
      with:
        doxyfile-path: 'docs/Doxyfile'

    - uses: ammaraskar/sphinx-action@master
      env:
        MADGINE_VERSION: ${{ steps.version.outputs.version }}
      with:
        docs-folder: "."
        pre-build-command: "pip install sphinx_rtd_theme doxysphinx;doxysphinx build docs doc/docs docs/doxygen"
        build-command: "sphinx-build -b html . doc -c docs"

    - uses: actions/checkout@v4
      with:
        ref: 'gh-pages'
        path: 'gh-pages'

    - name: Copy static files into repository
      run: |
        rm -rf gh-pages/doc
        cp -r doc gh-pages

    - name: "Updating gh-pages branch"
      run: |
        cd gh-pages
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add doc
        git commit -m "Updating generated docs"
        git push
